### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rhanajoy**
Updated the name of the "install and configure" article referred to in line 27 and fixed a couple of typos elsewhere.

### CODE REVIEW

**Comment by rhanajoy** [comment]
@m-hartmann I'm revising the title of the installation-setup-iothub.md article as part of https://dev.azure.com/bacx/content-requests/_workitems/edit/14296. Can you please change the title in this readme to match? Thanks!

**Review by m-hartmann — APPROVED** [review]

**Comment by m-hartmann** [comment]
@davidrunde please review/approve so we can merge the update

**Review by davidrunde — APPROVED** [review]

**Comment by davidrunde** [comment]
Done!

**Comment by rhanajoy** [comment]
@m-hartmann I noticed this PR is still open. Can you please merge or close it? Thanks!

**Pull request merged**
