### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by m-hartmann**
- Remove locale form links to honor user's language preferences
- Replace post-deployment steps with reference to public docs as single source of truth
- Propose minor tweaks to section headings

### CODE REVIEW

**Comment by m-hartmann** [comment]
Suggested changes to readme.md to be merged when the updated docs are published.

**Comment by m-hartmann** [comment]
@lmasieri FYI

**Review by lmasieri — APPROVED** [review]
LGTM! Thanks Michael

**Comment by m-hartmann** [comment]
@nickrm101 the linked content is live. Feel free to merge at your convenience.

**Review by nickrm101 — APPROVED** [review]

**Pull request merged**
